const EVENTS = {
  LOADED: 'APP_LOADED',
  UPDATE_TRACKERS: 'APP_UPDATE_TRACKERS',
  SHOW_NOTIFICATION: 'APP_SHOW_NOTIFICATION',
  RESTORE_APP: 'APP_RESTORE',
  RESET_DATA: 'APP_RESET_DATA',
};

export default EVENTS;
